name: Deploy with Terraform

on:
  push:
    branches:
      - main  # Déclenche l'action lorsque des changements sont poussés sur la branche `main`

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0  # Remplacez par la version de Terraform que vous utilisez
          cli_config_credentials_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Initialize Terraform
        run: terraform init

      - name: Plan Terraform deployment
        run: terraform plan -out=tfplan

      - name: Apply Terraform deployment
        run: terraform apply "tfplan"
        # Ajoutez l'option `-auto-approve` si vous souhaitez passer l'étape de confirmation automatique
